### ISSUE TITLE
Feedback vom Spengler vom 31.3.22

### ISSUE THREAD

**Issue by michael-spengler** [HaseFlrn/social-media-service#3]
Check if you might contribute / update https://deno.land/x/countries or reuse it... 

die lesbarkeit / wartbarkeit des codes kann m.E. an manchen stellen optimiert werden.

das frontend kann vllt. noch etwas weniger "werkstatt-like" gestaltet werden.

evtl. stärker als bisher mit "Mock Daten" arbeiten ... die Schnittstelle der API genau definieren - evtl. versionieren
**ggf.** https://www.npmjs.com/package/joi checken

**Comment by HaseFlrn** [comment]
@michael-spengler https://www.skypack.dev/view/joi
